[package]
name = "polyglot"
version = "0.0.1"
edition = "2021"

[dependencies]

[dev-dependencies]

[build-dependencies]
exercism = { path = "./exercism/rust" }
extension = { path = "./spiral/extension" }
test = { path = "./spiral/test" }
# proxy = { path = "./spiral/proxy" }
# cli = { path = "./spiral/cli" }

[lib]
path = "./spiral/cli/main.rs"



[workspace]

members = [
    "exercism/rust",
    "spiral/extension",
    "spiral/test",
    # "spiral/proxy",
    # "spiral/cli",
]
