[package]
name = "polyglot"
version = "0.0.1"
edition = "2021"

[workspace]

[dependencies]

[dev-dependencies]

[build-dependencies]
extension = { path = "./apps/spiral/temp/extension" }
test = { path = "./apps/spiral/temp/test" }
# proxy = { path = "./apps/spiral/temp/proxy" }
# cli = { path = "./apps/spiral/temp/cli" }
exercism = { path = "./examples/rust/exercism" }

[lib]
path = "./apps/spiral/temp/cli/main.rs"

members = [
    "examples/rust/exercism",
    "apps/spiral/temp/extension",
    "apps/spiral/temp/test",
    # "apps/spiral/temp/proxy",
    # "apps/spiral/temp/cli",
]
