[package]
name = "polyglot"
version = "0.0.1"
edition = "2021"

[workspace]

[dependencies]

[dev-dependencies]

[build-dependencies]
exercism = { path = "./examples/rust/exercism" }
extension = { path = "./spiral/extension" }
test = { path = "./spiral/test" }
# proxy = { path = "./spiral/proxy" }
# cli = { path = "./spiral/cli" }

[lib]
path = "./spiral/cli/main.rs"

members = [
    "examples/rust/exercism",
    "spiral/extension",
    "spiral/test",
    # "spiral/proxy",
    # "spiral/cli",
]
