[package]
name = "polyglot"
version = "0.0.1"
edition = "2021"

[dependencies]

[dev-dependencies]

[build-dependencies]
exercism = { path = "./rust/exercism" }
grover = { path = "./rust/grover" }
extension = { path = "./spiral/extension" }
test = { path = "./spiral/test" }
proxy = { path = "./spiral/proxy" }
cli = { path = "./spiral/cli" }

[lib]
path = "./spiral/cli/main.rs"



[workspace]

members = [
    "rust/exercism",
    "rust/grover",
    "spiral/extension",
    "spiral/test",
    "spiral/proxy",
    "spiral/cli",
]
