cargo-features = ["profile-rustflags"]

[package]
name = "chat"
version = "0.0.1"
edition = "2021"
rust-version = "1.69.0"

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "~4.1"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
rustflags = ["-C", "link-arg=-s"]
