[package]
name = "chat_contract"
version = "0.0.1"
edition = "2021"
workspace = "../../../"
description = ""
repository.workspace = true
license-file.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "~5.0.0-alpha.2"

sha2 = "~0.10"
multibase = "~0.9"
unsigned-varint = "~0.8"
